import type { Metadata } from 'next';
import { siteConfig } from '@/config/site';
import { absoluteUrl } from './utils';

export interface SeoOptions {
  title?: string;
  description?: string;
  /** Site-relative path. Drives both the canonical URL and OG url. */
  path?: string;
  /** Absolute or site-relative image path. Defaults to the dynamic OG route. */
  image?: string;
  type?: 'website' | 'article' | 'profile';
  publishedTime?: string;
  modifiedTime?: string;
  tags?: string[];
  /** Drafts and utility pages should not be indexed. */
  noIndex?: boolean;
}

/**
 * Compose page metadata.
 *
 * Every `generateMetadata` in the app funnels through here, which guarantees
 * that canonical URLs, OpenGraph and Twitter cards can never drift apart —
 * the most common SEO bug in hand-rolled Next.js apps.
 *
 * `metadataBase` is set once in the root layout, so relative image paths
 * resolve correctly without each caller repeating the origin.
 */
export function buildMetadata({
  title,
  description = siteConfig.description,
  path = '/',
  image,
  type = 'website',
  publishedTime,
  modifiedTime,
  tags,
  noIndex = false,
}: SeoOptions = {}): Metadata {
  const url = absoluteUrl(path, siteConfig.url);

  // Per-page OG images are generated by the `opengraph-image` route segment.
  // Falling back to the site-wide one keeps every page card-able.
  const ogImage = image ? absoluteUrl(image, siteConfig.url) : absoluteUrl('/opengraph-image', siteConfig.url);

  const resolvedTitle = title ? `${title} — ${siteConfig.name}` : `${siteConfig.name} — ${siteConfig.role}`;

  return {
    title: title ?? { absolute: resolvedTitle },
    description,
    alternates: {
      canonical: url,
      types: {
        'application/rss+xml': absoluteUrl('/rss.xml', siteConfig.url),
      },
    },
    openGraph: {
      title: resolvedTitle,
      description,
      url,
      siteName: siteConfig.name,
      locale: siteConfig.locale,
      type: type === 'profile' ? 'profile' : type,
      images: [{ url: ogImage, width: 1200, height: 630, alt: resolvedTitle }],
      ...(type === 'article' && {
        publishedTime,
        modifiedTime,
        authors: [siteConfig.name],
        tags,
      }),
    },
    twitter: {
      card: 'summary_large_image',
      title: resolvedTitle,
      description,
      images: [ogImage],
      creator: '@akshatgupta',
    },
    ...(noIndex && {
      robots: { index: false, follow: false },
    }),
  };
}
